### ISSUE TITLE
What's the difference between X-Engine and RocksDB?

### ISSUE THREAD

**Issue by JinheLin** [polardb/polardbx-engine#13]
X-Engine seems derived from RocksDB ? https://github.com/ApsaraDB/galaxyengine/tree/main/storage/xengine/core

What's the difference between X-Engine and RocksDB?

**Comment by chengxuntao-ntu** [comment]
Basic LSM-tree ideas are the same. But X-Engine has been tailored to suit some of Alibaba's own needs. For example, X-Engine does not allow infinite levels in the storage but uses up to 3 levels.

**Comment by luckywhu** [comment]
Please ref：[ X-Engine introduction](https://github.com/ApsaraDB/galaxyengine/wiki/X-Engine%E4%BA%8B%E5%8A%A1%E5%AD%98%E5%82%A8%E5%BC%95%E6%93%8E)  for more details
