### ISSUE TITLE
请问下标准版的版本兼容性

### ISSUE THREAD

**Issue by k1n9met** [polardb/polardbx-engine#33]
你好, 安装标准版之后执行show VARIABLES like 'version'; 看到版本是8.0.30, 然后在配置文件增加innodb_ddl_threads和innodb_ddl_buffer_size这两个参数就无法启动了, 看报错是不支持这两个参数,  但是这两个参数是8.0.27社区版本的, 按道理8.0.30版应该是包括了8.0.27版本的, 请问下这个要怎么处理呢

**Comment by sWildGold** [comment]
目前代码是18的，近期会开源30以上新版本，欢迎关注

**Comment by byte-drift** [comment]
8.0.32已开源
